In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

ROOT = Path.cwd()

# Nếu notebook đang chạy từ thư mục notebooks/
if not (ROOT / "data" / "raw").exists():
    ROOT = ROOT.parent

RAW = ROOT / "data" / "raw"
PROCESSED = ROOT / "data" / "processed"

PROCESSED.mkdir(parents=True, exist_ok=True)

print("ROOT:", ROOT)
print("RAW :", RAW)
print("PROCESSED:", PROCESSED)

ROOT: d:\DEEP\TQH-DU-LIEU-NHOM6
RAW : d:\DEEP\TQH-DU-LIEU-NHOM6\data\raw
PROCESSED: d:\DEEP\TQH-DU-LIEU-NHOM6\data\processed

In [2]:
df_nam_raw = pd.read_csv(
    RAW / "du_lieu_du_lich_nam.csv"
)

df_dp_raw = pd.read_csv(
    RAW / "du_lieu_du_lich_dia_phuong.csv"
)

print("Dataset theo năm:", df_nam_raw.shape)
print("Dataset địa phương:", df_dp_raw.shape)

display(df_nam_raw.head())
display(df_dp_raw.head())

Dataset theo năm: (10, 12)
Dataset địa phương: (700, 5)

,Năm,Doanh thu cơ sở lưu trú (Tỷ đồng),Doanh thu cơ sở lữ hành (Tỷ đồng),Khách cơ sở lưu trú phục vụ (Nghìn lượt),Khách nghỉ qua đêm (Nghìn lượt),Khách trong ngày (Nghìn lượt),Khách trong nước - cơ sở lưu trú (Nghìn lượt),Khách quốc tế - cơ sở lưu trú (Nghìn lượt),Khách cơ sở lữ hành phục vụ (Nghìn lượt),Khách trong nước - cơ sở lữ hành (Nghìn lượt),Khách quốc tế - cơ sở lữ hành (Nghìn lượt),Khách Việt Nam đi nước ngoài (Nghìn lượt)
0,2015,44711.5,30444.1,114011.00,..,..,102200.00,11811.00,12601.70,9288.70,2820.00,493.00
1,2016,48524.6,32530.3,129735.20,..,..,117037.80,12697.40,13651.00,9477.60,3584.50,588.80
2,2017,54383.3,36111.8,146585.20,..,..,132837.90,13747.30,15173.00,9918.40,4556.40,698.30
3,2018,59202.2,40371.2,159640.60,..,..,144683.10,14957.50,16966.00,11062.20,5125.90,777.90
4,2019,67019.3,44669.9,179365.49,..,..,162046.62,17318.87,18366.29,11791.16,5730.28,844.85

  Địa phương Cấp dữ liệu   Năm  Trạng thái Doanh thu du lịch lữ hành (Tỷ đồng)
0    CẢ NƯỚC     Cả nước  2015  Chính thức                             30444.1
1    CẢ NƯỚC     Cả nước  2016  Chính thức                             32530.3
2    CẢ NƯỚC     Cả nước  2017  Chính thức                             36111.8
3    CẢ NƯỚC     Cả nước  2018  Chính thức                             40371.2
4    CẢ NƯỚC     Cả nước  2019  Chính thức                             44669.9

In [3]:
print("===== DATASET THEO NĂM =====")
print(df_nam_raw.info())

print("\nMissing:")
print(df_nam_raw.isnull().sum())

print("\nDuplicate:", df_nam_raw.duplicated().sum())


print("\n\n===== DATASET ĐỊA PHƯƠNG =====")
print(df_dp_raw.info())

print("\nMissing:")
print(df_dp_raw.isnull().sum())

print("\nDuplicate:", df_dp_raw.duplicated().sum())

===== DATASET THEO NĂM =====
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Năm                                            10 non-null     str
 1   Doanh thu cơ sở lưu trú (Tỷ đồng)              10 non-null     float64
 2   Doanh thu cơ sở lữ hành (Tỷ đồng)              10 non-null     float64
 3   Khách cơ sở lưu trú phục vụ (Nghìn lượt)       10 non-null     float64
 4   Khách nghỉ qua đêm (Nghìn lượt)                10 non-null     str
 5   Khách trong ngày (Nghìn lượt)                  10 non-null     str
 6   Khách trong nước - cơ sở lưu trú (Nghìn lượt)  10 non-null     float64
 7   Khách quốc tế - cơ sở lưu trú (Nghìn lượt)     10 non-null     float64
 8   Khách cơ sở lữ hành phục vụ (Nghìn lượt)       10 non-null     float64
 9   Khách trong nước - cơ sở lữ hành (Nghìn lượt)  10 non-null     float64
 10  Khách quốc tế - cơ sở lữ hành (Nghìn lượt)     10 non-null     float64
 11  Khách Việt Nam đi nước ngoài (Nghìn lượt)      10 non-null     float64
dtypes: float64(9), str(3)
memory usage: 1.1 KB
None

Missing:
Năm                                              0
Doanh thu cơ sở lưu trú (Tỷ đồng)                0
Doanh thu cơ sở lữ hành (Tỷ đồng)                0
Khách cơ sở lưu trú phục vụ (Nghìn lượt)         0
Khách nghỉ qua đêm (Nghìn lượt)                  0
Khách trong ngày (Nghìn lượt)                    0
Khách trong nước - cơ sở lưu trú (Nghìn lượt)    0
Khách quốc tế - cơ sở lưu trú (Nghìn lượt)       0
Khách cơ sở lữ hành phục vụ (Nghìn lượt)         0
Khách trong nước - cơ sở lữ hành (Nghìn lượt)    0
Khách quốc tế - cơ sở lữ hành (Nghìn lượt)       0
Khách Việt Nam đi nước ngoài (Nghìn lượt)        0
dtype: int64

Duplicate: 0


===== DATASET ĐỊA PHƯƠNG =====
<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 5 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Địa phương                           700 non-null    str
 1   Cấp dữ liệu                          700 non-null    str
 2   Năm                                  700 non-null    int64
 3   Trạng thái                           700 non-null    str
 4   Doanh thu du lịch lữ hành (Tỷ đồng)  700 non-null    str
dtypes: int64(1), str(4)
memory usage: 27.5 KB
None

Missing:
Địa phương                             0
Cấp dữ liệu                            0
Năm                                    0
Trạng thái                             0
Doanh thu du lịch lữ hành (Tỷ đồng)    0
dtype: int64

Duplicate: 0

In [4]:
def dem_ky_hieu_hai_cham(df):
    return (
        df.astype(str)
          .apply(lambda col: col.str.strip().eq(".."))
          .sum()
    )

print("Số ký hiệu '..' trong dataset theo năm:")
print(dem_ky_hieu_hai_cham(df_nam_raw))

print("\nSố ký hiệu '..' trong dataset địa phương:")
print(dem_ky_hieu_hai_cham(df_dp_raw))

Số ký hiệu '..' trong dataset theo năm:
Năm                                              0
Doanh thu cơ sở lưu trú (Tỷ đồng)                0
Doanh thu cơ sở lữ hành (Tỷ đồng)                0
Khách cơ sở lưu trú phục vụ (Nghìn lượt)         0
Khách nghỉ qua đêm (Nghìn lượt)                  6
Khách trong ngày (Nghìn lượt)                    6
Khách trong nước - cơ sở lưu trú (Nghìn lượt)    0
Khách quốc tế - cơ sở lưu trú (Nghìn lượt)       0
Khách cơ sở lữ hành phục vụ (Nghìn lượt)         0
Khách trong nước - cơ sở lữ hành (Nghìn lượt)    0
Khách quốc tế - cơ sở lữ hành (Nghìn lượt)       0
Khách Việt Nam đi nước ngoài (Nghìn lượt)        0
dtype: int64

Số ký hiệu '..' trong dataset địa phương:
Địa phương                              0
Cấp dữ liệu                             0
Năm                                     0
Trạng thái                              0
Doanh thu du lịch lữ hành (Tỷ đồng)    12
dtype: int64

In [5]:
df_nam = df_nam_raw.copy()
df_dp = df_dp_raw.copy()

# Chuẩn hóa tên cột
df_nam.columns = df_nam.columns.str.strip()
df_dp.columns = df_dp.columns.str.strip()

# Chuẩn hóa khoảng trắng trong các cột dạng text
for col in df_nam.select_dtypes(include="object").columns:
    df_nam[col] = (
        df_nam[col]
        .astype(str)
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
    )

for col in df_dp.select_dtypes(include="object").columns:
    df_dp[col] = (
        df_dp[col]
        .astype(str)
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
    )

# Chuyển ký hiệu nguồn ".." thành dữ liệu thiếu
df_nam = df_nam.replace("..", np.nan)
df_dp = df_dp.replace("..", np.nan)

print("Đã chuẩn hóa khoảng trắng và xử lý ký hiệu '..'.")

Đã chuẩn hóa khoảng trắng và xử lý ký hiệu '..'.

C:\Users\Hoang\AppData\Local\Temp\ipykernel_23072\1221501449.py:9: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df_nam.select_dtypes(include="object").columns:
C:\Users\Hoang\AppData\Local\Temp\ipykernel_23072\1221501449.py:17: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df_dp.select_dtypes(include="object").columns:

In [7]:
# Lưu trạng thái của năm trước khi chuẩn hóa
df_nam["Trạng thái"] = df_nam["Năm"].astype(str).apply(
    lambda x: "Sơ bộ" if "Sơ bộ" in x else ""
)

# Tách năm 4 chữ số: "Sơ bộ 2024" -> 2024
df_nam["Năm"] = (
    df_nam["Năm"]
    .astype(str)
    .str.extract(r"(\d{4})")[0]
    .astype("int64")
)

# Các cột cần chuyển sang numeric
# Loại trừ Năm và Trạng thái
cot_so_nam = [
    col for col in df_nam.columns
    if col not in ["Năm", "Trạng thái"]
]

for col in cot_so_nam:
    df_nam[col] = pd.to_numeric(
        df_nam[col],
        errors="coerce"
    )

print(df_nam.dtypes)
display(df_nam[["Năm", "Trạng thái"]])

Năm                                                int64
Doanh thu cơ sở lưu trú (Tỷ đồng)                float64
Doanh thu cơ sở lữ hành (Tỷ đồng)                float64
Khách cơ sở lưu trú phục vụ (Nghìn lượt)         float64
Khách nghỉ qua đêm (Nghìn lượt)                  float64
Khách trong ngày (Nghìn lượt)                    float64
Khách trong nước - cơ sở lưu trú (Nghìn lượt)    float64
Khách quốc tế - cơ sở lưu trú (Nghìn lượt)       float64
Khách cơ sở lữ hành phục vụ (Nghìn lượt)         float64
Khách trong nước - cơ sở lữ hành (Nghìn lượt)    float64
Khách quốc tế - cơ sở lữ hành (Nghìn lượt)       float64
Khách Việt Nam đi nước ngoài (Nghìn lượt)        float64
Trạng thái                                           str
dtype: object

    Năm Trạng thái
0  2015
1  2016
2  2017
3  2018
4  2019
5  2020
6  2021
7  2022
8  2023
9  2024      Sơ bộ

In [8]:
# Năm phải là số nguyên
df_dp["Năm"] = pd.to_numeric(
    df_dp["Năm"],
    errors="raise"
).astype("int64")

# Doanh thu phải là numeric
df_dp["Doanh thu du lịch lữ hành (Tỷ đồng)"] = pd.to_numeric(
    df_dp["Doanh thu du lịch lữ hành (Tỷ đồng)"],
    errors="coerce"
)

# Chuẩn hóa các cột text quan trọng
for col in ["Địa phương", "Cấp dữ liệu", "Trạng thái"]:
    if col in df_dp.columns:
        df_dp[col] = (
            df_dp[col]
            .astype("string")
            .str.strip()
            .str.replace(r"\s+", " ", regex=True)
        )

print(df_dp.dtypes)

Địa phương                              string
Cấp dữ liệu                             string
Năm                                      int64
Trạng thái                              string
Doanh thu du lịch lữ hành (Tỷ đồng)    float64
dtype: object

In [9]:
print("Duplicate dataset năm trước:", df_nam.duplicated().sum())
print("Duplicate dataset địa phương trước:", df_dp.duplicated().sum())

df_nam = df_nam.drop_duplicates().reset_index(drop=True)
df_dp = df_dp.drop_duplicates().reset_index(drop=True)

print("\nSau xử lý:")
print("Dataset năm:", df_nam.duplicated().sum())
print("Dataset địa phương:", df_dp.duplicated().sum())

Duplicate dataset năm trước: 0
Duplicate dataset địa phương trước: 0

Sau xử lý:
Dataset năm: 0
Dataset địa phương: 0

In [10]:
print("Các cấp dữ liệu:")
print(df_dp["Cấp dữ liệu"].value_counts(dropna=False))

print("\nCác trạng thái:")
print(df_dp["Trạng thái"].value_counts(dropna=False))

print("\nCác năm:")
print(sorted(df_dp["Năm"].unique()))

print("\nSố địa phương khác nhau:")
print(df_dp["Địa phương"].nunique())

Các cấp dữ liệu:
Cấp dữ liệu
Tỉnh/thành    630
Vùng           60
Cả nước        10
Name: count, dtype: Int64

Các trạng thái:
Trạng thái
Chính thức    630
Sơ bộ          70
Name: count, dtype: Int64

Các năm:
[np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]

Số địa phương khác nhau:
70

In [11]:
print("===== DATASET NĂM =====")
print("Shape:", df_nam.shape)
print("Duplicate:", df_nam.duplicated().sum())
print("\nMissing:")
print(df_nam.isnull().sum())


print("\n===== DATASET ĐỊA PHƯƠNG =====")
print("Shape:", df_dp.shape)
print("Duplicate:", df_dp.duplicated().sum())
print("\nMissing:")
print(df_dp.isnull().sum())

===== DATASET NĂM =====
Shape: (10, 13)
Duplicate: 0

Missing:
Năm                                              0
Doanh thu cơ sở lưu trú (Tỷ đồng)                0
Doanh thu cơ sở lữ hành (Tỷ đồng)                0
Khách cơ sở lưu trú phục vụ (Nghìn lượt)         0
Khách nghỉ qua đêm (Nghìn lượt)                  6
Khách trong ngày (Nghìn lượt)                    6
Khách trong nước - cơ sở lưu trú (Nghìn lượt)    0
Khách quốc tế - cơ sở lưu trú (Nghìn lượt)       0
Khách cơ sở lữ hành phục vụ (Nghìn lượt)         0
Khách trong nước - cơ sở lữ hành (Nghìn lượt)    0
Khách quốc tế - cơ sở lữ hành (Nghìn lượt)       0
Khách Việt Nam đi nước ngoài (Nghìn lượt)        0
Trạng thái                                       0
dtype: int64

===== DATASET ĐỊA PHƯƠNG =====
Shape: (700, 5)
Duplicate: 0

Missing:
Địa phương                              0
Cấp dữ liệu                             0
Năm                                     0
Trạng thái                              0
Doanh thu du lịch lữ hành (Tỷ đồng)    12
dtype: int64

In [12]:
file_nam_clean = PROCESSED / "du_lieu_du_lich_nam_clean.csv"
file_dp_clean = PROCESSED / "du_lieu_du_lich_dia_phuong_clean.csv"

df_nam.to_csv(
    file_nam_clean,
    index=False,
    encoding="utf-8-sig"
)

df_dp.to_csv(
    file_dp_clean,
    index=False,
    encoding="utf-8-sig"
)

print("Đã tạo:")
print(file_nam_clean)
print(file_dp_clean)

Đã tạo:
d:\DEEP\TQH-DU-LIEU-NHOM6\data\processed\du_lieu_du_lich_nam_clean.csv
d:\DEEP\TQH-DU-LIEU-NHOM6\data\processed\du_lieu_du_lich_dia_phuong_clean.csv