# LÀM SẠCH VÀ CHUẨN BỊ DỮ LIỆU DU LỊCH VIỆT NAM

Notebook này thực hiện quá trình kiểm tra, làm sạch và chuẩn bị hai bộ dữ liệu du lịch Việt Nam trước khi đưa vào phân tích và trực quan hóa.

## Dữ liệu đầu vào

- `du_lieu_du_lich_nam.csv`: dữ liệu tổng hợp hoạt động du lịch theo năm.
- `du_lieu_du_lich_dia_phuong.csv`: dữ liệu doanh thu du lịch lữ hành theo địa phương.

## Mục tiêu

- Kiểm tra cấu trúc dữ liệu.
- Kiểm tra dữ liệu thiếu và ký hiệu đặc biệt.
- Kiểm tra bản ghi trùng lặp.
- Chuẩn hóa tên cột và dữ liệu dạng chuỗi.
- Chuẩn hóa kiểu dữ liệu.
- Chuẩn hóa thông tin năm 2024 là số liệu sơ bộ.
- Kiểm tra các giá trị bất thường.
- Xuất hai bộ dữ liệu sạch vào thư mục `data/processed/`.

> Hai file dữ liệu sau làm sạch sẽ được sử dụng thống nhất cho toàn bộ Chương 3.

## 1. Khai báo thư viện và đường dẫn

Sử dụng:

- `pandas` để đọc và xử lý dữ liệu.
- `numpy` để hỗ trợ xử lý dữ liệu thiếu.
- `pathlib` để quản lý đường dẫn file.

Notebook tự xác định thư mục gốc của project nên có thể chạy khi đặt trong thư mục `notebooks/`.

In [2]:
from pathlib import Path
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

# Thư mục gốc của project
ROOT = Path(r"D:\DEEP\TQH-DU-LIEU-NHOM6")

RAW = ROOT / "data" / "raw"
PROCESSED = ROOT / "data" / "processed"

PROCESSED.mkdir(parents=True, exist_ok=True)

print("Project root :", ROOT)
print("Raw data     :", RAW)
print("Processed    :", PROCESSED)

print("\nKiểm tra thư mục:")
print("ROOT tồn tại      :", ROOT.exists())
print("RAW tồn tại       :", RAW.exists())
print("PROCESSED tồn tại :", PROCESSED.exists())

Project root : D:\DEEP\TQH-DU-LIEU-NHOM6
Raw data     : D:\DEEP\TQH-DU-LIEU-NHOM6\data\raw
Processed    : D:\DEEP\TQH-DU-LIEU-NHOM6\data\processed

Kiểm tra thư mục:
ROOT tồn tại      : True
RAW tồn tại       : True
PROCESSED tồn tại : True

## 2. Đọc dữ liệu gốc

Hai bộ dữ liệu trong thư mục `data/raw/` được giữ nguyên để đảm bảo có thể đối chiếu lại với dữ liệu nguồn.

Dữ liệu sau xử lý sẽ được lưu riêng trong `data/processed/`.

In [3]:
file_nam = RAW / "du_lieu_du_lich_nam.csv"
file_dia_phuong = RAW / "du_lieu_du_lich_dia_phuong.csv"

print("File năm tồn tại:", file_nam.exists())
print("File địa phương tồn tại:", file_dia_phuong.exists())

df_nam_raw = pd.read_csv(file_nam)
df_dp_raw = pd.read_csv(file_dia_phuong)

print("\nKích thước dataset theo năm:", df_nam_raw.shape)
print("Kích thước dataset địa phương:", df_dp_raw.shape)

display(df_nam_raw.head())
display(df_dp_raw.head())

File năm tồn tại: True
File địa phương tồn tại: True

Kích thước dataset theo năm: (10, 12)
Kích thước dataset địa phương: (700, 5)

,Năm,Doanh thu cơ sở lưu trú (Tỷ đồng),Doanh thu cơ sở lữ hành (Tỷ đồng),Khách cơ sở lưu trú phục vụ (Nghìn lượt),Khách nghỉ qua đêm (Nghìn lượt),Khách trong ngày (Nghìn lượt),Khách trong nước - cơ sở lưu trú (Nghìn lượt),Khách quốc tế - cơ sở lưu trú (Nghìn lượt),Khách cơ sở lữ hành phục vụ (Nghìn lượt),Khách trong nước - cơ sở lữ hành (Nghìn lượt),Khách quốc tế - cơ sở lữ hành (Nghìn lượt),Khách Việt Nam đi nước ngoài (Nghìn lượt)
0,2015,44711.5,30444.1,114011.00,..,..,102200.00,11811.00,12601.70,9288.70,2820.00,493.00
1,2016,48524.6,32530.3,129735.20,..,..,117037.80,12697.40,13651.00,9477.60,3584.50,588.80
2,2017,54383.3,36111.8,146585.20,..,..,132837.90,13747.30,15173.00,9918.40,4556.40,698.30
3,2018,59202.2,40371.2,159640.60,..,..,144683.10,14957.50,16966.00,11062.20,5125.90,777.90
4,2019,67019.3,44669.9,179365.49,..,..,162046.62,17318.87,18366.29,11791.16,5730.28,844.85

  Địa phương Cấp dữ liệu   Năm  Trạng thái Doanh thu du lịch lữ hành (Tỷ đồng)
0    CẢ NƯỚC     Cả nước  2015  Chính thức                             30444.1
1    CẢ NƯỚC     Cả nước  2016  Chính thức                             32530.3
2    CẢ NƯỚC     Cả nước  2017  Chính thức                             36111.8
3    CẢ NƯỚC     Cả nước  2018  Chính thức                             40371.2
4    CẢ NƯỚC     Cả nước  2019  Chính thức                             44669.9

## 3. Kiểm tra cấu trúc dữ liệu ban đầu

Các bước kiểm tra gồm:

- số dòng và số cột;
- tên thuộc tính;
- kiểu dữ liệu;
- dữ liệu thiếu;
- bản ghi trùng lặp.

Mục tiêu là xác định các vấn đề cần xử lý trước khi trực quan hóa.

In [4]:
print("===== DATASET THEO NĂM =====")
print("Shape:", df_nam_raw.shape)

print("\nKiểu dữ liệu:")
df_nam_raw.info()

print("\nMissing:")
print(df_nam_raw.isnull().sum())

print("\nDuplicate:", df_nam_raw.duplicated().sum())


print("\n\n===== DATASET ĐỊA PHƯƠNG =====")
print("Shape:", df_dp_raw.shape)

print("\nKiểu dữ liệu:")
df_dp_raw.info()

print("\nMissing:")
print(df_dp_raw.isnull().sum())

print("\nDuplicate:", df_dp_raw.duplicated().sum())

===== DATASET THEO NĂM =====
Shape: (10, 12)

Kiểu dữ liệu:
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Năm                                            10 non-null     str
 1   Doanh thu cơ sở lưu trú (Tỷ đồng)              10 non-null     float64
 2   Doanh thu cơ sở lữ hành (Tỷ đồng)              10 non-null     float64
 3   Khách cơ sở lưu trú phục vụ (Nghìn lượt)       10 non-null     float64
 4   Khách nghỉ qua đêm (Nghìn lượt)                10 non-null     str
 5   Khách trong ngày (Nghìn lượt)                  10 non-null     str
 6   Khách trong nước - cơ sở lưu trú (Nghìn lượt)  10 non-null     float64
 7   Khách quốc tế - cơ sở lưu trú (Nghìn lượt)     10 non-null     float64
 8   Khách cơ sở lữ hành phục vụ (Nghìn lượt)       10 non-null     float64
 9   Khách trong nước - cơ sở lữ hành (Nghìn lượt)  10 non-null     float64
 10  Khách quốc tế - cơ sở lữ hành (Nghìn lượt)     10 non-null     float64
 11  Khách Việt Nam đi nước ngoài (Nghìn lượt)      10 non-null     float64
dtypes: float64(9), str(3)
memory usage: 1.1 KB

Missing:
Năm                                              0
Doanh thu cơ sở lưu trú (Tỷ đồng)                0
Doanh thu cơ sở lữ hành (Tỷ đồng)                0
Khách cơ sở lưu trú phục vụ (Nghìn lượt)         0
Khách nghỉ qua đêm (Nghìn lượt)                  0
Khách trong ngày (Nghìn lượt)                    0
Khách trong nước - cơ sở lưu trú (Nghìn lượt)    0
Khách quốc tế - cơ sở lưu trú (Nghìn lượt)       0
Khách cơ sở lữ hành phục vụ (Nghìn lượt)         0
Khách trong nước - cơ sở lữ hành (Nghìn lượt)    0
Khách quốc tế - cơ sở lữ hành (Nghìn lượt)       0
Khách Việt Nam đi nước ngoài (Nghìn lượt)        0
dtype: int64

Duplicate: 0


===== DATASET ĐỊA PHƯƠNG =====
Shape: (700, 5)

Kiểu dữ liệu:
<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 5 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Địa phương                           700 non-null    str
 1   Cấp dữ liệu                          700 non-null    str
 2   Năm                                  700 non-null    int64
 3   Trạng thái                           700 non-null    str
 4   Doanh thu du lịch lữ hành (Tỷ đồng)  700 non-null    str
dtypes: int64(1), str(4)
memory usage: 27.5 KB

Missing:
Địa phương                             0
Cấp dữ liệu                            0
Năm                                    0
Trạng thái                             0
Doanh thu du lịch lữ hành (Tỷ đồng)    0
dtype: int64

Duplicate: 0

## 4. Kiểm tra ký hiệu dữ liệu thiếu

Ngoài giá trị `NaN`, dữ liệu nguồn có thể sử dụng ký hiệu `..` để biểu diễn số liệu chưa có hoặc chưa được công bố.

Pandas không tự động xem `..` là dữ liệu thiếu, vì vậy cần kiểm tra riêng trước khi xử lý.

Các giá trị này không được tự động thay bằng `0`, vì:

- `0` có nghĩa là giá trị thực sự bằng không;
- dữ liệu thiếu có nghĩa là chưa có hoặc chưa được công bố.

In [5]:
def dem_ky_hieu_hai_cham(df):
    ket_qua = {}

    for col in df.columns:
        count = (
            df[col]
            .astype("string")
            .str.strip()
            .eq("..")
            .sum()
        )

        if count > 0:
            ket_qua[col] = int(count)

    return pd.Series(ket_qua, dtype="int64")


print("===== KÝ HIỆU '..' - DATASET THEO NĂM =====")
display(dem_ky_hieu_hai_cham(df_nam_raw))

print("\n===== KÝ HIỆU '..' - DATASET ĐỊA PHƯƠNG =====")
display(dem_ky_hieu_hai_cham(df_dp_raw))

===== KÝ HIỆU '..' - DATASET THEO NĂM =====

Khách nghỉ qua đêm (Nghìn lượt)    6
Khách trong ngày (Nghìn lượt)      6
dtype: int64

===== KÝ HIỆU '..' - DATASET ĐỊA PHƯƠNG =====

Doanh thu du lịch lữ hành (Tỷ đồng)    12
dtype: int64

## 5. Tạo bản sao và chuẩn hóa dữ liệu

Hai dataset gốc được sao chép trước khi làm sạch để không làm thay đổi dữ liệu trong `data/raw/`.

Các bước xử lý:

1. Loại bỏ khoảng trắng dư trong tên cột.
2. Loại bỏ BOM nếu có.
3. Chuẩn hóa khoảng trắng trong dữ liệu dạng chuỗi.
4. Chuyển ký hiệu `..` thành dữ liệu thiếu.

In [6]:
df_nam = df_nam_raw.copy()
df_dp = df_dp_raw.copy()


def chuan_hoa_co_ban(df):
    df = df.copy()

    # Chuẩn hóa tên cột
    df.columns = (
        df.columns
        .str.replace("\ufeff", "", regex=False)
        .str.strip()
    )

    # Chuẩn hóa dữ liệu dạng text nhưng vẫn giữ missing
    text_cols = df.select_dtypes(
        include=["object", "string"]
    ).columns

    for col in text_cols:
        df[col] = (
            df[col]
            .astype("string")
            .str.strip()
            .str.replace(r"\s+", " ", regex=True)
        )

    # ".." -> missing
    df = df.replace("..", pd.NA)

    return df


df_nam = chuan_hoa_co_ban(df_nam)
df_dp = chuan_hoa_co_ban(df_dp)

print("Đã chuẩn hóa dữ liệu cơ bản.")

Đã chuẩn hóa dữ liệu cơ bản.

## 6. Chuẩn hóa dữ liệu du lịch theo năm

Trong dữ liệu gốc, năm 2024 được biểu diễn dưới dạng `Sơ bộ 2024`.

Để thuận tiện cho phân tích:

- cột `Năm` được chuẩn hóa thành số nguyên;
- tạo thêm cột `Trạng thái`;
- 2015–2023 được ghi là `Chính thức`;
- 2024 được ghi là `Sơ bộ`.

Các chỉ tiêu doanh thu và lượng khách được chuyển sang kiểu số.

In [7]:
# Giữ lại nội dung gốc của cột Năm
nam_text = df_nam["Năm"].astype("string")

# Tạo cột Trạng thái
df_nam["Trạng thái"] = np.where(
    nam_text.str.contains("Sơ bộ", case=False, na=False),
    "Sơ bộ",
    "Chính thức"
)

# "Sơ bộ 2024" -> 2024
df_nam["Năm"] = pd.to_numeric(
    nam_text.str.extract(r"(\d{4})")[0],
    errors="raise"
).astype("int64")

# Các cột còn lại phải là numeric
cot_so_nam = [
    col
    for col in df_nam.columns
    if col not in ["Năm", "Trạng thái"]
]

for col in cot_so_nam:
    df_nam[col] = pd.to_numeric(
        df_nam[col],
        errors="coerce"
    )

print("Kiểu dữ liệu sau chuẩn hóa:")
print(df_nam.dtypes)

print("\nNăm và trạng thái:")
display(df_nam[["Năm", "Trạng thái"]])

Kiểu dữ liệu sau chuẩn hóa:
Năm                                                int64
Doanh thu cơ sở lưu trú (Tỷ đồng)                float64
Doanh thu cơ sở lữ hành (Tỷ đồng)                float64
Khách cơ sở lưu trú phục vụ (Nghìn lượt)         float64
Khách nghỉ qua đêm (Nghìn lượt)                  Float64
Khách trong ngày (Nghìn lượt)                    Float64
Khách trong nước - cơ sở lưu trú (Nghìn lượt)    float64
Khách quốc tế - cơ sở lưu trú (Nghìn lượt)       float64
Khách cơ sở lữ hành phục vụ (Nghìn lượt)         float64
Khách trong nước - cơ sở lữ hành (Nghìn lượt)    float64
Khách quốc tế - cơ sở lữ hành (Nghìn lượt)       float64
Khách Việt Nam đi nước ngoài (Nghìn lượt)        float64
Trạng thái                                           str
dtype: object

Năm và trạng thái:

    Năm  Trạng thái
0  2015  Chính thức
1  2016  Chính thức
2  2017  Chính thức
3  2018  Chính thức
4  2019  Chính thức
5  2020  Chính thức
6  2021  Chính thức
7  2022  Chính thức
8  2023  Chính thức
9  2024       Sơ bộ

## 7. Chuẩn hóa dữ liệu du lịch theo địa phương

Bộ dữ liệu địa phương được chuẩn hóa:

- `Năm` thành kiểu số nguyên;
- doanh thu thành dữ liệu số;
- `Địa phương`, `Cấp dữ liệu` và `Trạng thái` thành dữ liệu chuỗi;
- năm 2024 được xác định là số liệu sơ bộ;
- các năm trước được xác định là số liệu chính thức nếu trạng thái chưa được ghi rõ.

In [8]:
# Chuẩn hóa cột Năm
df_dp["Năm"] = pd.to_numeric(
    df_dp["Năm"]
    .astype("string")
    .str.extract(r"(\d{4})")[0],
    errors="raise"
).astype("int64")

# Chuẩn hóa doanh thu
cot_doanh_thu = "Doanh thu du lịch lữ hành (Tỷ đồng)"

df_dp[cot_doanh_thu] = pd.to_numeric(
    df_dp[cot_doanh_thu],
    errors="coerce"
)

# Chuẩn hóa các cột text
for col in ["Địa phương", "Cấp dữ liệu", "Trạng thái"]:
    if col in df_dp.columns:
        df_dp[col] = (
            df_dp[col]
            .astype("string")
            .str.strip()
            .str.replace(r"\s+", " ", regex=True)
        )

# Nếu chưa có cột Trạng thái thì tạo mới
if "Trạng thái" not in df_dp.columns:
    df_dp["Trạng thái"] = pd.NA

# Chuỗi rỗng -> missing
df_dp["Trạng thái"] = df_dp["Trạng thái"].replace("", pd.NA)

# Điền trạng thái còn thiếu dựa trên năm
df_dp["Trạng thái"] = df_dp["Trạng thái"].fillna(
    pd.Series(
        np.where(
            df_dp["Năm"].eq(2024),
            "Sơ bộ",
            "Chính thức"
        ),
        index=df_dp.index
    )
)

print(df_dp.dtypes)

display(df_dp.head())

Địa phương                              string
Cấp dữ liệu                             string
Năm                                      int64
Trạng thái                              string
Doanh thu du lịch lữ hành (Tỷ đồng)    Float64
dtype: object

,Địa phương,Cấp dữ liệu,Năm,Trạng thái,Doanh thu du lịch lữ hành (Tỷ đồng)
0,CẢ NƯỚC,Cả nước,2015,Chính thức,30444.1
1,CẢ NƯỚC,Cả nước,2016,Chính thức,32530.3
2,CẢ NƯỚC,Cả nước,2017,Chính thức,36111.8
3,CẢ NƯỚC,Cả nước,2018,Chính thức,40371.2
4,CẢ NƯỚC,Cả nước,2019,Chính thức,44669.9

## 8. Kiểm tra bản ghi trùng lặp

Các bản ghi giống hoàn toàn nhau có thể làm sai lệch kết quả thống kê và trực quan hóa.

Nếu phát hiện bản ghi trùng hoàn toàn, các bản ghi lặp được loại bỏ.

Không loại bỏ các dòng chỉ vì chúng có cùng năm hoặc cùng địa phương, vì đó có thể là những quan sát hợp lệ.

In [9]:
duplicate_nam = df_nam.duplicated().sum()
duplicate_dp = df_dp.duplicated().sum()

print("Duplicate dataset theo năm:", duplicate_nam)
print("Duplicate dataset địa phương:", duplicate_dp)

df_nam = (
    df_nam
    .drop_duplicates()
    .reset_index(drop=True)
)

df_dp = (
    df_dp
    .drop_duplicates()
    .reset_index(drop=True)
)

print("\nSau xử lý:")
print("Dataset theo năm:", df_nam.duplicated().sum())
print("Dataset địa phương:", df_dp.duplicated().sum())

Duplicate dataset theo năm: 0
Duplicate dataset địa phương: 0

Sau xử lý:
Dataset theo năm: 0
Dataset địa phương: 0

## 9. Kiểm tra cấp dữ liệu địa phương

Dataset địa phương bao gồm nhiều cấp dữ liệu:

- Cả nước;
- Vùng;
- Tỉnh/thành phố.

Các cấp này phải được phân biệt rõ trong Chương 3.

Ví dụ, khi xếp hạng tỉnh/thành, chỉ được sử dụng các dòng thuộc cấp tỉnh/thành để tránh tính trùng dữ liệu.

In [10]:
print("===== CẤP DỮ LIỆU =====")
print(df_dp["Cấp dữ liệu"].value_counts(dropna=False))

print("\n===== TRẠNG THÁI =====")
print(df_dp["Trạng thái"].value_counts(dropna=False))

print("\n===== CÁC NĂM =====")
print(sorted(df_dp["Năm"].unique()))

print("\n===== SỐ ĐỊA PHƯƠNG KHÁC NHAU =====")
print(df_dp["Địa phương"].nunique())

===== CẤP DỮ LIỆU =====
Cấp dữ liệu
Tỉnh/thành    630
Vùng           60
Cả nước        10
Name: count, dtype: Int64

===== TRẠNG THÁI =====
Trạng thái
Chính thức    630
Sơ bộ          70
Name: count, dtype: Int64

===== CÁC NĂM =====
[np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]

===== SỐ ĐỊA PHƯƠNG KHÁC NHAU =====
70

## 10. Kiểm tra giá trị bất thường

Giá trị ngoại lai (outlier) không đồng nghĩa với dữ liệu sai.

Một số địa phương lớn có thể có doanh thu cao hơn đáng kể so với các địa phương khác nhưng vẫn là giá trị hợp lệ.

Vì vậy notebook chỉ kiểm tra các giá trị bất thường, không tự động loại bỏ nếu chưa có căn cứ cho thấy đó là lỗi dữ liệu.

In [11]:
print("===== DATASET THEO NĂM =====")
display(df_nam.describe())

print("\n===== DOANH THU ĐỊA PHƯƠNG =====")
display(df_dp[[cot_doanh_thu]].describe())

# Kiểm tra giá trị âm
print(
    "\nSố doanh thu địa phương âm:",
    (df_dp[cot_doanh_thu] < 0).sum()
)

===== DATASET THEO NĂM =====

,Năm,Doanh thu cơ sở lưu trú (Tỷ đồng),Doanh thu cơ sở lữ hành (Tỷ đồng),Khách cơ sở lưu trú phục vụ (Nghìn lượt),Khách nghỉ qua đêm (Nghìn lượt),Khách trong ngày (Nghìn lượt),Khách trong nước - cơ sở lưu trú (Nghìn lượt),Khách quốc tế - cơ sở lưu trú (Nghìn lượt),Khách cơ sở lữ hành phục vụ (Nghìn lượt),Khách trong nước - cơ sở lữ hành (Nghìn lượt),Khách quốc tế - cơ sở lữ hành (Nghìn lượt),Khách Việt Nam đi nước ngoài (Nghìn lượt)
count,10.00000,10.000000,10.000000,10.000000,4.0,4.0,10.000000,10.000000,10.000000,10.000000,10.000000,10.00000
mean,2019.50000,56485.553000,39614.994000,150206.242000,132084.1575,39772.635,130706.901000,19499.328000,16664.123000,11678.717000,4492.615000,492.79100
std,3.02765,19871.978979,20566.030051,56717.873004,66953.680822,15076.903623,41813.768985,17188.071472,8971.073873,5937.406489,3070.470429,300.28698
min,2015.00000,23690.440000,8998.840000,63602.710000,43831.51,19771.19,60453.240000,3149.470000,3565.280000,3316.950000,246.010000,2.32000
25%,2017.25000,45664.775000,30965.650000,117942.050000,100677.445,33093.71,105909.450000,12032.600000,12864.025000,9335.925000,2595.322500,271.72500
50%,2019.50000,56039.980000,38241.500000,151872.920000,143673.04,42290.785,137967.275000,13905.645000,15160.040000,10490.300000,4070.450000,540.90000
75%,2021.75000,65065.025000,44378.802500,174434.267500,175079.7525,48969.71,157705.740000,16728.527500,18016.217500,12845.877500,5579.185000,734.23250
max,2024.00000,94101.410000,78990.470000,251896.820000,197159.04,54737.78,192273.000000,59623.760000,34371.220000,22968.480000,10656.530000,844.85000

===== DOANH THU ĐỊA PHƯƠNG =====

       Doanh thu du lịch lữ hành (Tỷ đồng)
count                                688.0
mean                           1727.398052
std                            6744.711651
min                                   0.02
25%                                   12.0
50%                                 41.115
75%                                211.335
max                               78990.47

Số doanh thu địa phương âm: 0

## 11. Kiểm tra dữ liệu sau làm sạch

Trước khi xuất file, dữ liệu được kiểm tra lại:

- kích thước;
- dữ liệu trùng;
- dữ liệu thiếu;
- kiểu dữ liệu;
- trạng thái năm;
- cấu trúc dữ liệu địa phương.

Các giá trị thiếu có nguồn gốc từ ký hiệu `..` được giữ dưới dạng missing thay vì tự động điền bằng `0`.

In [12]:
print("========== DATASET THEO NĂM ==========")

print("Shape:", df_nam.shape)
print("Duplicate:", df_nam.duplicated().sum())

print("\nTrạng thái:")
print(df_nam["Trạng thái"].value_counts(dropna=False))

print("\nMissing:")
print(df_nam.isnull().sum())

print("\nKiểu dữ liệu:")
print(df_nam.dtypes)


print("\n\n========== DATASET ĐỊA PHƯƠNG ==========")

print("Shape:", df_dp.shape)
print("Duplicate:", df_dp.duplicated().sum())

print("\nTrạng thái:")
print(df_dp["Trạng thái"].value_counts(dropna=False))

print("\nMissing:")
print(df_dp.isnull().sum())

print("\nKiểu dữ liệu:")
print(df_dp.dtypes)

========== DATASET THEO NĂM ==========
Shape: (10, 13)
Duplicate: 0

Trạng thái:
Trạng thái
Chính thức    9
Sơ bộ         1
Name: count, dtype: int64

Missing:
Năm                                              0
Doanh thu cơ sở lưu trú (Tỷ đồng)                0
Doanh thu cơ sở lữ hành (Tỷ đồng)                0
Khách cơ sở lưu trú phục vụ (Nghìn lượt)         0
Khách nghỉ qua đêm (Nghìn lượt)                  6
Khách trong ngày (Nghìn lượt)                    6
Khách trong nước - cơ sở lưu trú (Nghìn lượt)    0
Khách quốc tế - cơ sở lưu trú (Nghìn lượt)       0
Khách cơ sở lữ hành phục vụ (Nghìn lượt)         0
Khách trong nước - cơ sở lữ hành (Nghìn lượt)    0
Khách quốc tế - cơ sở lữ hành (Nghìn lượt)       0
Khách Việt Nam đi nước ngoài (Nghìn lượt)        0
Trạng thái                                       0
dtype: int64

Kiểu dữ liệu:
Năm                                                int64
Doanh thu cơ sở lưu trú (Tỷ đồng)                float64
Doanh thu cơ sở lữ hành (Tỷ đồng)                float64
Khách cơ sở lưu trú phục vụ (Nghìn lượt)         float64
Khách nghỉ qua đêm (Nghìn lượt)                  Float64
Khách trong ngày (Nghìn lượt)                    Float64
Khách trong nước - cơ sở lưu trú (Nghìn lượt)    float64
Khách quốc tế - cơ sở lưu trú (Nghìn lượt)       float64
Khách cơ sở lữ hành phục vụ (Nghìn lượt)         float64
Khách trong nước - cơ sở lữ hành (Nghìn lượt)    float64
Khách quốc tế - cơ sở lữ hành (Nghìn lượt)       float64
Khách Việt Nam đi nước ngoài (Nghìn lượt)        float64
Trạng thái                                           str
dtype: object


========== DATASET ĐỊA PHƯƠNG ==========
Shape: (700, 5)
Duplicate: 0

Trạng thái:
Trạng thái
Chính thức    630
Sơ bộ          70
Name: count, dtype: Int64

Missing:
Địa phương                              0
Cấp dữ liệu                             0
Năm                                     0
Trạng thái                              0
Doanh thu du lịch lữ hành (Tỷ đồng)    12
dtype: int64

Kiểu dữ liệu:
Địa phương                              string
Cấp dữ liệu                             string
Năm                                      int64
Trạng thái                              string
Doanh thu du lịch lữ hành (Tỷ đồng)    Float64
dtype: object

## 12. Xuất dữ liệu đã làm sạch

Sau khi kiểm tra, hai dataset được lưu vào thư mục `data/processed/`.

Hai file này là dữ liệu đầu vào chính thức cho Chương 3:

- `du_lieu_du_lich_nam_clean.csv`
- `du_lieu_du_lich_dia_phuong_clean.csv`

TV2, TV3 và TV4 sử dụng chung hai file này và không tự làm sạch lại dữ liệu theo cách riêng.

In [13]:
file_nam_clean = (
    PROCESSED /
    "du_lieu_du_lich_nam_clean.csv"
)

file_dp_clean = (
    PROCESSED /
    "du_lieu_du_lich_dia_phuong_clean.csv"
)

df_nam.to_csv(
    file_nam_clean,
    index=False,
    encoding="utf-8-sig"
)

df_dp.to_csv(
    file_dp_clean,
    index=False,
    encoding="utf-8-sig"
)

print("Đã xuất dữ liệu thành công:")

print(file_nam_clean)
print(file_dp_clean)

Đã xuất dữ liệu thành công:
D:\DEEP\TQH-DU-LIEU-NHOM6\data\processed\du_lieu_du_lich_nam_clean.csv
D:\DEEP\TQH-DU-LIEU-NHOM6\data\processed\du_lieu_du_lich_dia_phuong_clean.csv

## 13. Xác nhận file sau khi xuất

Hai file vừa tạo được đọc lại để kiểm tra lần cuối rằng quá trình lưu dữ liệu thành công và cấu trúc dữ liệu không bị thay đổi.

In [14]:
check_nam = pd.read_csv(file_nam_clean)
check_dp = pd.read_csv(file_dp_clean)

print("Dataset năm clean:", check_nam.shape)
print("Dataset địa phương clean:", check_dp.shape)

print("\nTrạng thái dataset năm:")
print(check_nam["Trạng thái"].value_counts(dropna=False))

print("\nDuplicate:")
print("Theo năm:", check_nam.duplicated().sum())
print("Địa phương:", check_dp.duplicated().sum())

print("\nHoàn tất quá trình làm sạch dữ liệu.")

Dataset năm clean: (10, 13)
Dataset địa phương clean: (700, 5)

Trạng thái dataset năm:
Trạng thái
Chính thức    9
Sơ bộ         1
Name: count, dtype: int64

Duplicate:
Theo năm: 0
Địa phương: 0

Hoàn tất quá trình làm sạch dữ liệu.

# KẾT LUẬN

Quá trình làm sạch và chuẩn bị dữ liệu đã hoàn thành.

Các bước chính đã thực hiện:

1. Đọc và khảo sát dữ liệu gốc.
2. Kiểm tra dữ liệu thiếu và ký hiệu `..`.
3. Kiểm tra dữ liệu trùng lặp.
4. Chuẩn hóa tên cột và dữ liệu dạng chuỗi.
5. Chuẩn hóa kiểu dữ liệu.
6. Chuẩn hóa `Sơ bộ 2024` thành `Năm = 2024` và `Trạng thái = Sơ bộ`.
7. Kiểm tra các giá trị bất thường.
8. Kiểm tra lại dữ liệu sau xử lý.
9. Xuất hai dataset sạch.

Dữ liệu sau xử lý được lưu tại:

`data/processed/du_lieu_du_lich_nam_clean.csv`

`data/processed/du_lieu_du_lich_dia_phuong_clean.csv`

Hai dataset này sẽ được sử dụng thống nhất cho các nội dung phân tích và trực quan hóa ở Chương 3.